"""Adde index and unique cosntraint to post title

Revision ID: 00847145eb7f
Revises: 2ed884f18250
Create Date: 2019-12-08 02:00:13.706850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00847145eb7f'
down_revision = '2ed884f18250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_title'), 'post', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_title'), table_name='post')
    # ### end Alembic commands ###
