"""added dash title

Revision ID: 02e78e766732
Revises: 28c0e1a30782
Create Date: 2019-12-23 14:08:31.156678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02e78e766732'
down_revision = '28c0e1a30782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('dash_title', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'dash_title')
    # ### end Alembic commands ###
