"""Message and comment language

Revision ID: 28c0e1a30782
Revises: 00847145eb7f
Create Date: 2019-12-09 01:21:12.580545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28c0e1a30782'
down_revision = '00847145eb7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('language', sa.String(length=5), nullable=True))
    op.add_column('message', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'language')
    op.drop_column('comments', 'language')
    # ### end Alembic commands ###
